// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dapamrqjdmvjavnexkme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGFtcnFqZG12amF2bmV4a21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjg5NjYsImV4cCI6MjA1OTk0NDk2Nn0.EjiK_Y5F6GJnKL75G3bLl9RPGWqQAAUcMkCT-KB23og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);